server.port=8085
spring.application.name=ecommerce

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5431/ecommerce
spring.datasource.username=testuser
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=d33f86ad6e0274d9f2a6965f85142a8afbf7a13443fa9966a5bdb99110a3a12ec823f412f3e8d63fc2ffb32f112cef1a5c2d6d558cbc0021d9a779bb632a6530
jwt.expiration=86400000
